# Generated by Django 4.2.24 on 2025-09-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopAtSinItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField()),
                ('category', models.CharField(max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('stock', models.IntegerField(default=0)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.FloatField(default=0.0)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
